AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: oregonkeypair
      SecurityGroupIds:
      - sg-d9c9dca0
      InstanceType: t2.large
      ImageId: ami-bf4193c7
      Tags:
        -
          Key: Name
          Value: craigexchange
      UserData:
        Fn::Base64: !Sub |     # No more Fn::Join needed
          #!/bin/bash
          yum install git -y
          sudo -u ec2-user bash -c 'cd /home/ec2-user; git clone https://github.com/craigwongva/exchange.git > /tmp/u10 2>&1 '
          sudo -u ec2-user bash -c '/home/ec2-user/exchange/userdata > /tmp/u20 2>&1 '
Outputs:
  publicip:
    Value: !GetAtt MyInstance.PublicIp
